// generated by compile -asmhdr from package bytealg

#define const_offsetX86HasSSE42 80
#define const_offsetX86HasAVX2 67
#define const_offsetX86HasPOPCNT 74
#define const_offsetS390xHasVX 80
#define const_offsetPPC64HasPOWER9 67
#define const_PrimeRK 16777619
#define const_MaxBruteForce 64
