// generated by compile -asmhdr from package syscall

#define const_SYS_FCNTL 72
#define const_SYS_EPOLL_CTL 233
#define const_SYS_EPOLL_PWAIT 281
#define const_SYS_EPOLL_CREATE1 291
#define const_SYS_EPOLL_PWAIT2 441
#define const_EPOLLIN 1
#define const_EPOLLOUT 4
#define const_EPOLLERR 8
#define const_EPOLLHUP 16
#define const_EPOLLRDHUP 8192
#define const_EPOLLET 2147483648
#define const_EPOLL_CLOEXEC 524288
#define const_EPOLL_CTL_ADD 1
#define const_EPOLL_CTL_DEL 2
#define const_EPOLL_CTL_MOD 3
#define EpollEvent__size 12
#define EpollEvent_Events 0
#define EpollEvent_Data 4
