// generated by compile -asmhdr from package notsha256

#define const_Size 32
#define const_BlockSize 64
#define const_chunk 64
#define const_init0 1779033703
#define const_init1 3144134277
#define const_init2 1013904242
#define const_init3 2773480762
#define const_init4 1359893119
#define const_init5 2600822924
#define const_init6 528734635
#define const_init7 1541459225
#define digest__size 112
#define digest_h 0
#define digest_x 32
#define digest_nx 96
#define digest_len 104
